apiVersion: apps/v1
kind: Deployment
metadata:
  name: lister-deployment
  labels:
    app: lister
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lister
  template:
    metadata:
      labels:
        app: lister
    spec:
      containers:
      - name: lister
        image: mahakal0510/lister:0.1.2
        resources:
          limits:
            memory: "256Mi"  
            cpu: "100m"      
          requests:
            memory: "128Mi"  
            cpu: "50m"       